### PR TITLE
Add surf geom cloud aerosol jacobians

### PR DESCRIPTION
**Pull request by karpob**
## Description
An issue was created by some cryptically named user raising the issue that elevation ( and the associated latitude and longitude, SurfGeom) wasn't fully wired into the CRTM. While I was at it changing things, I added the capability to output Cloud and Aerosol Jacobians. 

## Issue(s) addressed

Resolves https://github.com/karpob/pycrtm/issues/97

## Dependencies
None

## Impact

None
## Checklist

- [ x] I have performed a self-review of my own code
- [ x] I have made corresponding changes to the documentation
- [ x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by BenjaminTJohnson — APPROVED** [review]

**Review by StegmannJCSDA — CHANGES_REQUESTED** [review]
As a suggestion, would it be possible to change the `_jac` ending to `_K` for consistency with the CRTM, or to a more explicit `_jacobian`?

**Comment by karpob** [comment]
> As a suggestion, would it be possible to change the `_jac` ending to `_K` for consistency with the CRTM, or to a more explicit `_jacobian`?

I changed the python facing outputs to be  CloudEffectiveRadiusK, CloudConcentrationK, CloudFractionK, AerosolEffectiveRadiusK, AerosolConcentrationK, output_cloud_K, output_aerosol_K to be more consistent with the other Jacobians outputs. I made the internal variables on the fortran side to be Jacobian, to be consistent with other Jacobians in the interface. 

That work?

**Comment by StegmannJCSDA** [comment]
Sounds good.

**Comment by karpob** [comment]
Awesome, I'll merge it. Thanks Guys!

**Pull request merged**
